# Generated by Django 5.1.5 on 2025-02-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_rating_product_color_product_dpi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='switch_type',
        ),
    ]
